# Generated by Django 5.2.1 on 2025-06-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_of_creation', models.DateField()),
                ('main_subject', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard'), ('6', 'Extreme')], max_length=1)),
                ('categories', models.ManyToManyField(related_name='questions', to='examwbteacher.category')),
                ('original_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examwbteacher.paper')),
            ],
        ),
    ]
