# Generated by Django 5.2.1 on 2025-06-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('FIB', 'Fill in the Blanks'), ('SAQ', 'Short Answer Question'), ('LAQ', 'Long Answer Question'), ('TrueFalse', 'True/False Question'), ('Descriptive', 'Descriptive Question')], max_length=50),
        ),
    ]
