# Generated by Django 5.2.1 on 2025-06-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='examwbteacher.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='examwbteacher.subtopic'),
        ),
    ]
