# Generated by Django 5.2.1 on 2025-06-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0003_subtopic_remove_question_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='examwbteacher.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(null=True),
        ),
    ]
