# Generated by Django 5.2.1 on 2025-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0005_question_image_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='question_pdfs/'),
        ),
    ]
