# Generated by Django 5.2.1 on 2025-06-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0006_question_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='subtopics', to='examwbteacher.category'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='main_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='examwbteacher.category'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='examwbteacher.unit'),
        ),
    ]
