# Generated by Django 5.2.1 on 2025-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examwbteacher', '0007_unit_subtopic_categories_alter_paper_main_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='No Question Text'),
        ),
    ]
